import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const rootDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIST_DIR = path.join(rootDir, "dist");
const GLYPHS_DIR = path.join(rootDir, "glyphs");
const GLYPH_WEIGHTS = ["regular", "light", "bold", "fill", "duotone"];
const GLYPH_VIEWBOX = "0 0 256 256";

fs.rmSync(DIST_DIR, { recursive: true, force: true });
for (const dir of ["glyphs", "react/icons", "react-native/icons"]) fs.mkdirSync(path.join(DIST_DIR, dir), { recursive: true });

const names = buildGlyphs();
if (names.length === 0) {
  console.error("❌ No glyphs found in glyphs/regular/");
  process.exit(1);
}

const header = "/**\n * UnIcon glyphs. Generated by scripts/build.js, do not edit.\n * Copyright © Unifesto Private Limited\n */\n";
fs.writeFileSync(path.join(DIST_DIR, "index.d.ts"), header + glyphTypes(names), "utf-8");
for (const platform of ["react", "react-native"]) writePlatform(names, platform, header);

console.log(`✓ Built ${names.length} glyphs → dist/ (glyphs/, react/, react-native/, index.d.ts)`);

// ─── Glyphs ──────────────────────────────────────────────────────────────────
// Source: glyphs/<weight>/<name>.svg. Every glyph needs a regular weight; any
// other weight it lacks falls back to regular at render time.

function toPascal(name) {
  return name.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

// Parse one source SVG into path entries. A plain path is stored as its `d`
// string; anything carrying extra attributes becomes { d, rule?, duo? }.
function parseGlyphSvg(svg, where, errors) {
  const viewBox = svg.match(/viewBox="([^"]*)"/)?.[1];
  if (viewBox !== GLYPH_VIEWBOX) errors.push(`${where}: viewBox must be "${GLYPH_VIEWBOX}" (got "${viewBox}")`);
  if (/stroke/.test(svg)) errors.push(`${where}: has strokes, run Outline Stroke + Flatten before export`);

  const paths = [];
  const rest = svg
    .replace(/<\?xml[^>]*>/, "")
    .replace(/<svg[^>]*>|<\/svg>/g, "")
    .replace(/<path\s+([^>]*?)\s*\/?>(?:<\/path>)?/g, (_, attrs) => {
      const a = Object.fromEntries([...attrs.matchAll(/([\w-]+)="([^"]*)"/g)].map((m) => [m[1], m[2]]));
      for (const key of Object.keys(a)) {
        if (!["d", "opacity", "fill", "fill-rule", "clip-rule"].includes(key)) errors.push(`${where}: unsupported path attribute "${key}"`);
      }
      if (a.fill && a.fill !== "currentColor") errors.push(`${where}: hard-coded fill "${a.fill}", remove it so the glyph can be tinted`);
      if (!a.d) errors.push(`${where}: path without d`);
      const rule = a["fill-rule"] === "evenodd" ? "evenodd" : undefined;
      const duo = a.opacity !== undefined ? true : undefined;
      paths.push(rule || duo ? { d: a.d, rule, duo } : a.d);
      return "";
    });
  if (rest.trim()) errors.push(`${where}: only <path> elements are supported, found: ${rest.trim().slice(0, 60)}`);
  return paths;
}

function buildGlyphs() {
  const regularDir = path.join(GLYPHS_DIR, "regular");
  if (!fs.existsSync(regularDir)) return [];

  const svgsIn = (dir) =>
    fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith(".svg")).map((f) => path.basename(f, ".svg")) : [];
  const names = svgsIn(regularDir).sort();
  const errors = [];
  const data = {};

  for (const weight of GLYPH_WEIGHTS) {
    for (const name of svgsIn(path.join(GLYPHS_DIR, weight))) {
      if (!names.includes(name)) errors.push(`${weight}/${name}.svg: no regular/${name}.svg`);
    }
  }

  for (const name of names) {
    data[name] = {};
    for (const weight of GLYPH_WEIGHTS) {
      const file = path.join(GLYPHS_DIR, weight, `${name}.svg`);
      if (fs.existsSync(file)) data[name][weight] = parseGlyphSvg(fs.readFileSync(file, "utf-8"), `${weight}/${name}.svg`, errors);
    }
  }

  const pascal = new Map();
  for (const name of names) {
    const p = toPascal(name);
    if (pascal.has(p)) errors.push(`glyph names "${pascal.get(p)}" and "${name}" both export ${p}`);
    pascal.set(p, name);
  }

  if (errors.length) {
    console.error(`\n❌ ${errors.length} glyph error(s):\n  ${errors.join("\n  ")}\n`);
    process.exit(1);
  }

  // One data module per glyph so bundlers that tree-shake (Next.js) ship only
  // the glyphs a page imports. index.js is the full map, used by UnGlyph.
  const notice = "// Generated from glyphs/*. Shapes derived from Phosphor Icons (MIT), see LICENSE.\n";
  for (const name of names) {
    fs.writeFileSync(path.join(DIST_DIR, "glyphs", `${name}.js`), `${notice}export default ${JSON.stringify(data[name])};\n`, "utf-8");
  }
  const ids = names.map((n) => [n, `g_${n.replace(/-/g, "_")}`]);
  fs.writeFileSync(
    path.join(DIST_DIR, "glyphs", "index.js"),
    `${notice}${ids.map(([n, id]) => `import ${id} from "./${n}.js";`).join("\n")}\n\nexport default {\n${ids.map(([n, id]) => `  "${n}": ${id},`).join("\n")}\n};\n`,
    "utf-8"
  );
  return names;
}

function writePlatform(names, platform, header) {
  const native = platform === "react-native";
  const dir = path.join(DIST_DIR, platform);
  const write = (file, body) => fs.writeFileSync(path.join(dir, file), `${header}\n${body}`, "utf-8");

  write(
    "base.js",
    `import React from "react";
${native ? `import Svg, { Path } from "react-native-svg";\n` : ""}
// Renders one glyph's data. Props match Phosphor's.
export function renderGlyph(glyph, {
  weight = "regular",
  size = 24,
  color = ${native ? `"#000"` : `"currentColor"`},
  mirrored = false,
  duotoneColor,
  duotoneOpacity = 0.2,
  style,
  ...props
}) {
  const paths = glyph[weight] || glyph.regular;
  return React.createElement(
    ${native ? "Svg" : `"svg"`},
    {${native ? "" : ` xmlns: "http://www.w3.org/2000/svg",`} viewBox: "${GLYPH_VIEWBOX}", width: size, height: size, fill: color, color, style: ${native ? `mirrored ? [style, { transform: [{ scaleX: -1 }] }] : style` : `mirrored ? { ...style, transform: "scaleX(-1)" } : style`}, ...props },
    paths.map((p, i) =>
      typeof p === "string"
        ? React.createElement(${native ? "Path" : `"path"`}, { key: i, d: p })
        : React.createElement(${native ? "Path" : `"path"`}, {
            key: i,
            d: p.d,
            fillRule: p.rule,
            ...(p.duo && { fill: duotoneColor ?? color, opacity: duotoneOpacity }),
          })
    )
  );
}

// A named glyph component, e.g. Ticket.
export function glyph(data, name) {
  const Component = (props) => renderGlyph(data, props);
  Component.displayName = name;
  return Component;
}
`
  );

  for (const name of names) {
    const P = toPascal(name);
    write(
      `icons/${name}.js`,
      `import data from "../../glyphs/${name}.js";\nimport { glyph } from "../base.js";\n\nexport const ${P} = glyph(data, "${P}");\nexport { ${P} as ${P}Icon };\n`
    );
  }

  write(
    "un-glyph.js",
    `import glyphs from "../glyphs/index.js";
import { renderGlyph } from "./base.js";

/**
 * UnGlyph - any glyph by name. Imports every glyph, so prefer named
 * components (\`<Ticket />\`) on the web where bundle size matters.
 *
 * @example
 * <UnGlyph name="ticket" weight="fill" size={24} color="#fff" />
 */
export function UnGlyph({ name, ...props }) {
  const glyph = glyphs[name];
  if (!glyph) {
    console.warn(\`UnGlyph: glyph "\${name}" not found\`);
    return null;
  }
  return renderGlyph(glyph, props);
}

export const glyphNames = ${JSON.stringify(names)};
`
  );

  write(
    "index.js",
    `export { UnGlyph, glyphNames } from "./un-glyph.js";\n` +
      names.map((n) => `export { ${toPascal(n)}, ${toPascal(n)}Icon } from "./icons/${n}.js";`).join("\n") +
      "\n"
  );
}

function glyphTypes(names) {
  const named = names
    .map((n) => `export declare const ${toPascal(n)}: Icon;\nexport declare const ${toPascal(n)}Icon: Icon;`)
    .join("\n");
  return `
/** Available glyph names (single-colour SVG icons) */
export type GlyphName =
${names.map((n) => `  | "${n}"`).join("\n") || "  never"};

/** Glyph weight. Weights a glyph doesn't define render as "regular". */
export type IconWeight = "thin" | "light" | "regular" | "bold" | "fill" | "duotone";

/** Props shared by UnGlyph and every named glyph component */
export interface IconProps {
  /** Width and height (default: 24) */
  size?: number | string;
  /** Fill colour (default: "#000" native, "currentColor" web) */
  color?: string;
  /** Weight (default: "regular") */
  weight?: IconWeight;
  /** Flip horizontally, e.g. for RTL */
  mirrored?: boolean;
  /** Colour of the duotone background layer (default: color) */
  duotoneColor?: string;
  /** Opacity of the duotone background layer (default: 0.2) */
  duotoneOpacity?: number;
  style?: any;
  [prop: string]: any;
}

/** A glyph component, e.g. \`Ticket\` */
export type Icon = React.FC<IconProps>;

export declare const UnGlyph: React.FC<IconProps & { name: GlyphName }>;
export declare const glyphNames: GlyphName[];

${named}
`;
}
